[theme]
base            = "dark"
primaryColor    = "#6366f1"
backgroundColor = "#090d16"
secondaryBackgroundColor = "#0f172a"
textColor       = "#f8fafc"
font            = "sans serif"

[server]
headless             = true
enableStaticServing  = true
maxUploadSize        = 200

[browser]
gatherUsageStats = false
